version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - PYTHON_ENV=development
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"